### ISSUE TITLE
UnboundLocalError: cannot access local variable 'red' where it is not associated with a value

### ISSUE THREAD

**Issue by neilzone** [FriedrichFroebel/brother_ql_web#7] opened 2023-11-12 17:49 UTC
# Setup:

* Raspberry Pi, running Raspberry Pi OS 6.1.0-rpi4-rpi-v8
* Brother QL-710W, with 62mm endless labels
* `brother_ql_web` installed via `pip install brother_ql_web`
* Running it via `python -m brother_ql_web --configuration /home/pi/labelmaker/config.json`

Config file:

```
{
  "server": {
    "port": 8013,
    "host": "",
    "log_level": "WARNING",
    "additional_font_folder": ""
  },
  "printer": {
    "model": "QL-710W",
    "printer": "file:///dev/usb/lp0"
  },
  "label": {
    "default_size": "62",
    "default_orientation": "standard",
    "default_font_size": 70,
    "default_fonts": [
      {"family": "Minion Pro",      "style": "Semibold"},
      {"family": "Linux Libertine", "style": "Regular"},
      {"family": "DejaVu Serif",    "style": "Book"}
    ]
  },
  "website": {
    "html_title": "Label Designer",
    "page_title": "Brother QL Label Designer",
    "page_headline": "Design your label and print it…"
  }
}
```

* I have checked the printer path using `udevadm info -a /dev/usb/lp*`

# What happens

When I enter some text and click "Print", I do not get a label, and I see the following error in the Pi's terminal:

```
Traceback (most recent call last):
  File "/home/pi/labelmaker/lib/python3.11/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/pi/labelmaker/lib/python3.11/site-packages/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "/home/pi/labelmaker/lib/python3.11/site-packages/brother_ql_web/web.py", line 118, in print_text
    qlr = generate_label(
          ^^^^^^^^^^^^^^^
  File "/home/pi/labelmaker/lib/python3.11/site-packages/brother_ql_web/labels.py", line 220, in generate_label
    red=red,
        ^^^
UnboundLocalError: cannot access local variable 'red' where it is not associated with a value
```

(I have also tried using 29*90 labels, and select "29x90 die cut" in the web ui; instead, I got an error `raise ValueError("Bad image dimensions: %s. Expecting: %s." % (im.size, dots_expected))`)

# What I'd expect to happen

Label prints.

Any help would be most welcome.

**Comment by FriedrichFroebel** [comment] 2023-11-21 19:22
Sorry for the delay. This appears to be a duplicate of #4 and should work with the Git version. I did not yet release a new version to PyPI.

**Comment by neilzone** [comment] 2023-11-22 09:35
Thank you! I wasn't able to make it work on the basis of a quick test, but I will try again when I can.

**Comment by FriedrichFroebel** [comment] 2023-11-23 17:56
A new release has been pushed to PyPI which should fix this issue.

**Closed by FriedrichFroebel** 2023-11-23 17:56 UTC
Labels: bug

**Comment by neilzone** [comment] 2023-11-24 10:31
> A new release has been pushed to PyPI which should fix this issue.

Confirmed as working via PyPi. Thank you very much!
